services:
  bff:
    build: ./urban-kicks-bff
    ports:
      - "8080:8080"
    environment:
      COGNITO_ISSUER_URI: ${COGNITO_ISSUER_URI}
      COGNITO_CLIENT_ID: ${COGNITO_CLIENT_ID}
      CATALOG_URL: http://catalog:8082
      ORDERS_URL: http://orders:8081
      NOTIFY_URL: http://notify:8083
      REPORT_URL: http://report:8084
      AUDIT_URL: http://audit:8085
    depends_on:
      - catalog
      - orders
      - notify
      - report
      - audit

  catalog:
    build: ./urban-kicks-catalog
    ports:
      - "8082:8082"
    environment:
      DB_URL: ${CATALOG_DB_URL}
      DB_USER: ${CATALOG_DB_USER}
      DB_PASSWORD: ${CATALOG_DB_PASSWORD}

  orders:
    build: ./urban-kicks-orders
    ports:
      - "8081:8081"
    environment:
      DB_URL: ${ORDERS_DB_URL}
      DB_USER: ${ORDERS_DB_USER}
      DB_PASSWORD: ${ORDERS_DB_PASSWORD}

  notify:
    build: ./urban-kicks-notify
    ports:
      - "8083:8083"

  report:
    build: ./urban-kicks-report
    ports:
      - "8084:8084"

  audit:
    build: ./urban-kicks-audit
    ports:
      - "8085:8085"